fix(DataTable): update sort order to go ASC -> DESC -> NONE
carbon-design-system/carbon-components-react pull request #1535
Opened 2018-11-07 17:23 UTC by joshblack

Updates sort order and tooltip to follow NONE -> ASC -> DESC -> NONE order.

#### Changelog

**New**

**Changed**

* Update to sorting state and tools under Data Table
* Update to Table Header to better reflect logic for next tooltip

**Removed**

2018-11-08 01:31 UTC, alisonjoseph approved these changes
Thanks for updating this!

2018-11-08 13:38 UTC, austinbruch commented on src/components/DataTable/TableHeader.js
> +        return 'Rort rows by this header in ascending order';
@joshblack Typo `Rort` vs `Sort`?
```suggestion
        return 'Sort rows by this header in ascending order';
```

2018-11-08 13:39 UTC, austinbruch commented on src/components/DataTable/TableHeader.js
> +        return 'Rort rows by this header in descending order';
@joshblack Same as above...
```suggestion
        return 'Sort rows by this header in descending order';
```

2018-11-09 15:43 UTC, joshblack commented
Thanks @austinbruch!

2018-11-09 17:30 UTC, lovemecomputer requested changes
looks good! tho i think there's one CSS change that could make the UX of the component more clear:

in the gif, note that when returned to default sort state, the :focus state remains, and judging by the icon, it makes it look like it has been returned to ASC. that ASC icon (and focus border) remains until clicking outside of the element:
![sorting01](https://user-images.githubusercontent.com/3846271/48278223-8c593180-e412-11e8-994f-07cdd13e65c9.gif)

2018-11-09 17:35 UTC, joshblack commented
@lovemecomputer agreed! Added this issue: https://github.com/IBM/carbon-components/issues/1421

2018-11-09 17:47 UTC, lovemecomputer approved these changes

2018-11-09 17:48 UTC, lovemecomputer commented
@joshblack cool! since this is captured in that issue and the fix may come in a separate PR, i'm approving these changes here~

2018-11-09 18:04 UTC, joshblack commented
Real quick for anyone looking to merge, let me add `aria-sort` support as well in this PR!

2018-11-12 16:20 UTC, joshblack commented
Updated!

2018-11-13 15:28 UTC, merged

2020-09-24 08:22 UTC, reinisg commented
Hello!
Sorry for old conversation update, but I have question about this. Is it possible to set one column as default ASC sorted? Is there any parameters which pass to table column? 

Regards, Reinis